### PR TITLE
feature/added-token-info-to-footer

### PR DESCRIPTION
**Pull request by csmartinsfct**

### CODE REVIEW

**Comment by jjperezaguinaga** [comment]
@csmartinsfct you need to add the file as well 😅 

https://pull-132-mybit-io-dev.now.sh/static/files/MYB_Token_Information.pdf

**Comment by csmartinsfct** [comment]
@jjperezaguinaga added missing file!

**Comment by jjperezaguinaga** [comment]
https://pull-132-mybit-io-dev.now.sh/static/files/MYB_Token_Information.pdf now is working ☺️

**Comment by jjperezaguinaga** [comment]
Why did you close this PR? 🤔

**Comment by csmartinsfct** [comment]
Must have done it by mistake. I was cleaning up my fork. Restored.

**Comment by jjperezaguinaga** [comment]
This PR being like
im back

**Pull request merged**
