### PR TITLE
[#9] Add opacity to Consensus 2018 as the event has already been completed

### PR DESCRIPTION
**Pull request by trowacat**
fixed [#9](https://github.com/MyBitFoundation/mybit-issues/issues/9)

_Summary_
The event date that has passed has been removed from the community page.

### CODE REVIEW

**Comment by jjperezaguinaga** [comment]
Hi @trowacat ! We are looking into "hiding" the event by reducing the opacity of it, not removing it altogether. The idea is to showcase the events we are having but "disabling" the ones in the past. Here's more or less what it would look like:

image

The component in question that needs to be modified is the `Highlight.js` one, and probably just needs an extra parameter like `isDisabled` or so to do those changes css wise.

**Comment by trowacat** [comment]
@jjperezaguinaga I'm sorry I misunderstood, I'll update my PR to address what was actually wanted. Thank you for the mock-up!

**Comment by jjperezaguinaga** [comment]
Thanks!

**Comment by jjperezaguinaga** [comment]
Hi @trowacat, we are cleaning up our repository to include automatic builds through Zeit.co, so we are going to close your PR for now, please feel free to reopen it tomorrow!

**Pull request closed without merging**
